DROP TABLE T_TDM_OPERACAO;

CREATE TABLE T_TDM_OPERACAO(
    CD_OPERACAO        INT           NOT NULL ,
    CD_MERCADORIA      INT           NOT NULL ,
    NM_TIPO_NEGOCIO    VARCHAR(15)   NOT NULL ,
    NM_TIPO_MERCADORIA VARCHAR(15)   NOT NULL ,
    QT_PRODUTOS        INT           NOT NULL ,
    NM_MERCADORIA      VARCHAR(15)   NOT NULL ,
    VL_TOTAL           DOUBLE        NOT NULL
);

ALTER TABLE T_TDM_OPERACAO ADD CONSTRAINT T_TDM_OPERACAO_PK PRIMARY KEY (CD_OPERACAO) ;
ALTER TABLE T_TDM_OPERACAO CHANGE CD_OPERACAO CD_OPERACAO INT NOT NULL AUTO_INCREMENT;